/**
 * The SharedProvidersConstants enum defines constants for shared service providers.
 */
export enum SharedProvidersConstants {
	TRANSLATE_REPOSITORY = 'TRANSLATE_REPOSITORY',
	TOKEN_REPOSITORY = 'TOKEN_REPOSITORY',
	AUTH_REPOSITORY = 'AUTH_REPOSITORY',
	SESSION_STORAGE_REPOSITORY = 'SESSION_STORAGE_REPOSITORY',
	NOTIFICATION_REPOSITORY = 'NOTIFICATION_REPOSITORY',
}
